[package]
name = "aoc2021_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
anyhow = "1.0.51"
clap = "3.0.0-beta.5"
